/**
 * BigInt is a special numeric type that provides support for integers of random length.
 * A BigInt is generated by appending n to the end of an integer literal or by calling the function BigInt that 
    generates BigInt from strings, numbers, etc.
 */

// EXAMPLE:
// 2 ways of declaring Big Int variables
const bigintvar = 67423478234689887894747472389477823647n;
// OR
const bigintvar = BigInt("67423478234689887894747472389477823647");
const bigintFromNumber = BigInt(10); // same as 10n

//common math operations can be done on BigInt as regular numbers. But BigInt and regular numbers cannot be mixed in the expression.

Example: alert(3n + 2n); // 5
alert(7n / 2n); // 3
alert(8n + 2); // Error: Cannot mix BigInt and other types

// Here the division returns the result rounded towards zero, without the decimal part. Thus, all operations on BigInt return BigInt.
// BigInt and regular numbers must be explicitly converted using either BigInt() or Number(), as shown below:
// EXAMPLE:
let bigintvar = 6n;
let numvar = 3;
// number to bigint
alert(bigintvar + BigInt(numvar)); // 9
// bigint to number
alert(Number(bigintvar) + numvar); // 9

// In the above example, if the bigintvar is too large that it won’t fit the number type, then extra bits will be cut off.

// Talking about comparison and boolean operations on BigInt, it works fine.

// EXAMPLE:

alert(8n > 2n); // true
alert(4n > 2); // true
// Even though numbers and BigInts belong to different types, they can be equal ==, but not strictly equal ===.

// EXAMPLE:

alert(5 == 5n); // true
alert(5 === 5n); // false

// When inside if or other boolean operations, BigInts behave like numbers.

// EXAMPLE

if (0n) {
  // never executes
}
//  BigInt 0n is falsy, other values are considered to be truthy.
// Boolean operators, such as ||, && and others also work perfectly with Bigints similar to numbers.

// EXAMPLE

alert(1n || 2);
// 1, here 1n is considered truthy
alert(0n || 2);
// 2, here 0n is considered falsy
